services:
  backend:
    restart: always
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    command: bash -c "alembic upgrade head &&
      uvicorn main:app
      --host 0.0.0.0
      --app-dir backend
      --port 8000 --reload"
    ports:
      - "8000:8000"
    volumes:
      - ./:/app:rw
    depends_on:
      - db
    networks:
      - backend
    env_file:
      - ./.env
  db:
    image: postgres:16-bullseye
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
  redis:
    restart: unless-stopped
    image: redis:7.2.4-alpine
    expose:
      - 6379
    networks:
      - backend
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8000

volumes:
  db: {}

networks:
  backend:
    # Use a custom driver which takes special options
    driver: bridge
